### ISSUE TITLE
Could not find value for 'collectd_enabled'

### ISSUE THREAD

**Issue by daks** [electrical/puppet-bucky#16]
Hello,

I just discovered your Puppet module, and trying a basic configuration failed with an error message about collectd_enabled.
My manifest looks like this

```
class { 'bucky': }
```

with client 3.4. This test was done on Vagrant as you can see on this output

```
Error: Failed to parse template bucky/etc/bucky/bucky.conf.erb:
  Filepath: /usr/lib/ruby/vendor_ruby/puppet/parser/templatewrapper.rb
  Line: 81
  Detail: Could not find value for 'collectd_enabled' at /tmp/vagrant-puppet-1/modules-0/bucky/templates/etc/bucky/bucky.conf.erb:31
 at /tmp/vagrant-puppet-1/modules-0/bucky/manifests/config.pp:40 on node standalone.puppet.vagrant Error: Failed to parse template bucky/etc/bucky/bucky.conf.erb:
  Filepath: /usr/lib/ruby/vendor_ruby/puppet/parser/templatewrapper.rb
  Line: 81
  Detail: Could not find value for 'collectd_enabled' at /tmp/vagrant-puppet-1/modules-0/bucky/templates/etc/bucky/bucky.conf.erb:31
 at /tmp/vagrant-puppet-1/modules-0/bucky/manifests/config.pp:40 on node standalone.puppet.vagrant
```

I've read that this module is half-abandoned (your comment on a PR) but if you need motivation to work on it, I'm interested :)

**Comment by Wernervdmerwe** [comment]
@daks, (or anyone else facing this issue) there is a syntax error in /etc/puppet/modules/bucky/templates/etc/bucky/bucky.conf.erb

Line 31 should read:
<%- if scope.lookupvar('bucky::collectd_enabled') == true -%>
